const termsList = [
  "Accepting the Terms",
  "Privacy and Use of Your Personal Information",
  "Description of the Services",
  "Account Information from Third Party Sites",
  "Masoon Offers and Third-Party Links",
  "Your Registration Information",
  "Your Use of the Service",
  "Use with Your Mobile Device",
  "Online and Mobile Alerts",
  "Rights You Grant to Us",
  "Masoon’s Intellectual Property Rights",
  "Access and Interference",
  "Rules for Posting",
  "Social Media Sites",
  "Disclaimer of Representations and Warranties",
  "Financial Information is not Financial Planning, Broker or Tax Advice",
  "Limitations on Masoon’s Liability",
  "Your Indemnification of Masoon",
  "Ending your relationship with Masoon",
  "Modifications",
  "Governing Law and Forum for Disputes",
  "Allegations of Copyright and Trademark Infringements",
];
export default termsList;
